version: '2.1'
orbs:
  snyk: snyk/snyk@2.3.0
jobs:
  security_scan:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run: npm install
      - snyk/install
      - run:
          command: snyk version
          name: Which version of snyk is installed
      - run:
          command: snyk code test
          name: Run code scan
workflows:
  security_workflow:
    jobs:
      - security_scan