version: 2.1
orbs:
  snyk: snyk/snyk@2.3.0

jobs:
  snyk-security-scan:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - run:
          name: Install Snyk to HTML
          command: npm install -g snyk-to-html
      
      - snyk/scan:
          name: Snyk Open Source Scan
          command: test
          fail-on-issues: false
          monitor-on-build: false
          token-variable: SNYK_TOKEN
          additional-arguments: --json-file-output=oss-results.json

      - snyk/scan:
          name: Snyk Code Scan
          command: code test
          fail-on-issues: false
          monitor-on-build: false
          token-variable: SNYK_TOKEN
          additional-arguments: --json-file-output=code-results.json

      - run:
          name: Generate HTML reports
          when: always
          command: |
            snyk-to-html -i oss-results.json -o oss-report.html
            snyk-to-html -i code-results.json -o code-report.html
      
      - store_artifacts:
          path: oss-report.html
      - store_artifacts:
          path: code-report.html

workflows:
  security-workflow:
    jobs:
      - snyk-security-scan